### ISSUE TITLE
拍照崩溃

### ISSUE THREAD

**Issue by itdais** [donglua/PhotoPicker#165]
红米note2系统5.0  三星手机4.4    和google手机系统7.0 都是拍照出现崩溃的情况
即使第一次不崩溃 多拍几张也会崩溃!

**Comment by donglua** [comment]
权限加了吗，试试 0.9.5 会不会~~

**Comment by itdais** [comment]
权限肯定有的 用我自己的拍照时没有问题的! 
就是用的当前最新的版本!

**Comment by hebiao6446** [comment]
权限都配置好了，我的手机是红米 note2 




FATAL EXCEPTION: main
                                                                        Process: com.han2in.han2stylist, PID: 11594
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.han2in.han2stylist/me.iwf.photopicker.PhotoPickerActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.Toolbar
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                         Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.Toolbar
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:896)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                            at me.iwf.photopicker.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:39)
                                                                            at android.app.Activity.performCreate(Activity.java:5975)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                            at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                            at android.os.Looper.loop(Looper.java:194) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:896) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                            at me.iwf.photopicker.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:39) 
                                                                            at android.app.Activity.performCreate(Activity.java:5975) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                            at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                            at android.os.Looper.loop(Looper.java:194) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                                                                         Caused by: java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
                                                                            at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:891)
                                                                            at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:356)
                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                            at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
                                                                            at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                                            at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                                            at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:896) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                            at me.iwf.photopicker.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:39) 
                                                                            at android.app.Activity.performCreate(Activity.java:5975) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                            at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                            at android.os.Looper.loop(Looper.java:194) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by hebiao6446** [comment]
我的是红米最新MIUI  ， Samsung 我这边没有崩溃
