### ISSUE TITLE
android 7.0 打开相机崩溃

### ISSUE THREAD

**Issue by WanLiLi** [donglua/PhotoPicker#179]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                               at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
                                                               at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                               at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
                                                               at com.mbox.cn.tool.ImageCaptureManager.dispatchTakePictureIntent(ImageCaptureManager.java:70)
                                                               at com.mbox.cn.controller.photopicker.PhotoPickerFragment.openCamera(PhotoPickerFragment.java:226)
                                                               at com.mbox.cn.controller.photopicker.PhotoPickerFragment.access$400(PhotoPickerFragment.java:47)
                                                               at com.mbox.cn.controller.photopicker.PhotoPickerFragment$4.onClick(PhotoPickerFragment.java:183)
                                                               at com.mbox.cn.controller.photopicker.PhotoGridAdapter$1.onClick(PhotoGridAdapter.java:89)

**Comment by zoubo** [comment]
解决了吗？我也遇到同样的问题

**Comment by heming0512** [comment]
应该是provider 设置有问题。源码中读取的是 String authority = mContext.getApplicationInfo().packageName + ".provider";   检查manifest里provider的路径

**Comment by buobao** [comment]
请问，这个问题是怎么解决的呢？
