### ISSUE TITLE
4.4打开相册报错

### ISSUE THREAD

**Issue by liyihan333** [donglua/PhotoPicker#195]
java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to android.app.Activity
                                                                                 at cn.bingoogolapple.photopicker.imageloader.BGAGlideImageLoader.display(BGAGlideImageLoader.java:43)
                                                                                 at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:64)
                                                                                 at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:68)
                                                                                 at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:72)
                                                                                 at cn.bingoogolapple.photopicker.imageloader.BGAImage.display(BGAImage.java:76)
                                                                                 at cn.bingoogolapple.photopicker.adapter.BGAPhotoPickerAdapter.fillData(BGAPhotoPickerAdapter.java:66)
                                                                                 at cn.bingoogolapple.photopicker.adapter.BGAPhotoPickerAdapter.fillData(BGAPhotoPickerAdapter.java:34)
                                                                                 at cn.bingoogolapple.androidcommon.adapter.BGARecyclerViewAdapter.onBindViewHolder(BGARecyclerViewAdapter.java:98)
                                                                                 at cn.bingoogolapple.androidcommon.adapter.BGARecyclerViewAdapter.onBindViewHolder(BGARecyclerViewAdapter.java:32)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6310)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6343)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5289)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5552)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                                 at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                                 at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3537)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3266)
                                                                                 at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                                 at android.view.View.layout(View.java:14852)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4642)
                                                                                 at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                                                                 at android.view.View.layout(View.java:14852)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4642)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                 at android.view.View.layout(View.java:14852)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4642)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                 at android.view.View.layout(View.java:14852)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4642)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                 at android.view.View.layout(View.java:14852)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4642)
                                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                 at android.view.View.layout(View.java:14852)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4642)
                                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                 at android.view.View.layout(View.java:14852)
                                                                                 at android.view.ViewGroup.layout(ViewGroup.java:4642)
                                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1995)
                                                                             	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.jav

**Comment by donglua** [comment]
https://github.com/bingoogolapple/BGAPhotoPicker-Android

**Comment by donglua** [comment]
这 issue 不是我这个项目的，别人改的我不管
