### ISSUE TITLE
glide:compiler:4.4.0

### ISSUE THREAD

**Issue by dadakkk** [donglua/PhotoPicker#235]
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in 1/base.apk:classes5.dex)
                                                                            at me.iwf.photopicker.adapter.PhotoGridAdapter.onBindViewHolder(PhotoGridAdapter.java:118)
                                                                            at me.iwf.photopicker.adapter.PhotoGridAdapter.onBindViewHolder(PhotoGridAdapter.java:27)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)

**Comment by leov1** [comment]
I got the same issue, using glide 4.4.0 or 3.7.0

**Comment by leov1** [comment]
@dadakkk  I downgrade the glide version to 4.1.1, it resolved.

**Comment by paixols** [comment]
Same issue with Louvre image library

**Comment by chihung93** [comment]
same issue
