### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes

### ISSUE THREAD

**Issue by jerinamathews** [donglua/PhotoPicker#261]
Getting this error when trying to start PhotoPicker. Am using Glide 4.7.1.

java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/--package---v6-kkcbUr35NFt7CltbbmQ==/split_lib_dependencies_apk.apk)
        at me.iwf.photopicker.adapter.PhotoGridAdapter.onBindViewHolder(PhotoGridAdapter.java:118)
        at me.iwf.photopicker.adapter.PhotoGridAdapter.onBindViewHolder(PhotoGridAdapter.java:27)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
        at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1613)
        at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:687)
        at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:609)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-30 12:21:06.839 2742-2742/com.rectfy.flip E/AndroidRuntime:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by TwinsOd** [comment]
I have this error too

**Comment by chenfd99** [comment]
+1

**Comment by HuJianChong** [comment]
+1

**Comment by TwinsOd** [comment]
I changed glide version to 'com.github.bumptech.glide:glide:4.1.1', it worked

**Comment by jingzz1** [comment]
+1

**Comment by zc5689** [comment]
+1

**Comment by KnifeStone** [comment]
+1

**Comment by aotian16** [comment]
+1

must use glide:4.1.1

**Comment by 18743206721** [comment]
必须使用glide4.1.1

**Comment by SugerQ** [comment]
+1

**Comment by jeetwide** [comment]
@TwinsOd Thanks brother. you saved my day. I also changed it to glide:4.1.1 to make it work.

**Comment by yangzhensu** [comment]
4.3.1 works for me.

**Comment by SuperBeagleDog** [comment]
I got a solution. The problem is each module used differ version of glide... , your guys should unite your versions of gilde on each Module(Make them have same version).  and you should care that use ‘implementation’ to load gilde on gradle of each module.

**Comment by loumzy** [comment]
+1

**Comment by Raiden18** [comment]
+1

**Comment by Sunaina015** [comment]
I am using glide 4.1.1 and also getting the same issue .

**Comment by emailsubjekt** [comment]
I'm not even using Glide in the class that crashes when I start it!? I start a class that doesn't even have Glide in it, it's connected to an adapter where glide is commented out and I'm using something else and this is the error

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.blabla.blabla, PID: 12705
    java.lang.NoSuchMethodError: No virtual method override(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.blabla.blabla-blablablablablablablablabla==/base.apk)
        at com.fxn.adapters.InstantImageAdapter.<init>(InstantImageAdapter.java:40)
        at com.fxn.pix.Pix.initialize(Pix.java:432)
        at com.fxn.pix.Pix.onCreate(Pix.java:325)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)


What the hell is going on. Glide should be better protected against this type of thing.

**Comment by letuszou** [comment]
楼上的大哥们  解决了 说下  
但行好事 莫问前程

**Comment by SuperBeagleDog** [comment]
> 楼上的大哥们 解决了 说下
> 但行好事 莫问前程

我已经在楼上回复了，不懂得翻译一下吗？大概意思就是：确保所有modules的glide的版本一致就行

**Comment by incomingflyingbrick** [comment]
解决了几把

**Comment by AceInAndroid** [comment]
是因为其他库里面使用了不同版本的glide，
Because other libraries use different versions of glide，you can use  'exclude' method resolve this error

**Comment by enwokoma** [comment]
> 是因为其他库里面使用了不同版本的glide，
> Because other libraries use different versions of glide，you can use 'exclude' method resolve this error

How is that?? I cannot find any other libraries in my project that uses a different version of glide
