### ISSUE TITLE
华为X2闪退,其他手机都行...

### ISSUE THREAD

**Issue by xiyanglove** [donglua/PhotoPicker#88]
华为X2闪退,其他手机都行...

**Comment by donglua** [comment]
报什么错没有

**Comment by xiyanglove** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rxjr.rxcd.beta/me.iwf.photopicker.PhotoPickerActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3952)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5273)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at me.iwf.photopicker.fragment.PhotoPickerFragment.onDetach(PhotoPickerFragment.java:235)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1202)
	at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1349)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:699)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at me.iwf.photopicker.PhotoPickerActivity.onCreate(PhotoPickerActivity.java:75)
	at android.app.Activity.performCreate(Activity.java:6041)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283)

**Comment by donglua** [comment]
我用X2测试了最新版本没有闪退呀...
