### ISSUE TITLE
问下作者有没有遇到这个错误

### ISSUE THREAD

**Issue by Loyea** [donglua/PhotoPicker#96]
```
java.lang.IllegalStateException: Unable to create layer for PopupWindow$PopupBackgroundView
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:330)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5643)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
```

错误信息很少，我甚至找不到哪里引发的错误，更别说如何复现了= = 而且出错的都是6.0和6.0.1的机器。
我很绝望，找遍自己项目的代码都找不到原因，所以想问下作者你有在你的项目里遇到过这个错吗？  

如果没有打扰了

**Comment by donglua** [comment]
目前没有遇到过呢。。会经常出现的吗
