### ISSUE TITLE
when Trget 23 or above it's need run time permissions check 

### ISSUE THREAD

**Issue by MostafaAnter** [donglua/PhotoPicker#98]
`java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:142)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=29337, uid=10062 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                          at android.os.Parcel.readException(Parcel.java:1599)
                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                          at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                          at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                          at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:29)
                                                                          at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
                                                                          at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
                                                                          at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
                                                                          at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
                                                                          at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
                                                                          at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
                                                                          at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
                                                                          at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) `

**Comment by donglua** [comment]
See #50

**Comment by MostafaAnter** [comment]
i solved it my self but i ask why u don't solve this trice inside the library to make my life more easy, thanks:)

**Comment by jounghu** [comment]
why i click camera(photo),there no response!

**Comment by donglua** [comment]
fixed
